spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      console.settings.trace: false
      spring.h2.console.settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:cred-app
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    #hibernate:
    properties:
      hibernate.format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html